services:
  # Service pour la base de données MySQL
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sechoir
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  # Service Adminer pour gérer la base de données
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8090:8080"

volumes:
  db_data: